package com.quat.englishService.service;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import jakarta.mail.internet.MimeMessage;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

@Service
public class EmailService {

    private static final Logger logger = LoggerFactory.getLogger(EmailService.class);

    private final JavaMailSender mailSender;

    @Value("${app.mail-from}")
    private String fromEmail;

    @Value("${app.mail-to}")
    private String toEmail;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    public void sendVocabularyEmail(String content) {
        try {
            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

            helper.setFrom(fromEmail);
            helper.setTo(toEmail);
            helper.setSubject("Daily English Vocabulary - " + LocalDate.now().format(DateTimeFormatter.ofPattern("MMM dd, yyyy")));
            helper.setText(formatEmailContent(content), true);

            mailSender.send(message);
            logger.info("Vocabulary email sent successfully to {}", toEmail);

        } catch (Exception e) {
            logger.error("Failed to send vocabulary email: {}", e.getMessage(), e);
        }
    }

    private String formatEmailContent(String content) {
        return String.format("""
                <!DOCTYPE html>
                <html>
                <head>
                    <meta charset="UTF-8">
                    <style>
                        body { font-family: Arial, sans-serif; line-height: 1.6; margin: 20px; }
                        .header { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
                        .word-section { margin: 20px 0; padding: 15px; background-color: #f8f9fa; border-left: 4px solid #3498db; }
                        .word-title { color: #2980b9; font-size: 1.2em; font-weight: bold; margin-bottom: 10px; }
                        pre { white-space: pre-wrap; font-family: Arial, sans-serif; }
                        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #bdc3c7; color: #7f8c8d; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>📚 Daily English Vocabulary</h1>
                        <p>Date: %s</p>
                    </div>
                    
                    <div class="word-section">
                        <pre>%s</pre>
                    </div>
                    
                    <div class="footer">
                        <p>Keep learning and improving your English vocabulary! 🌟</p>
                        <p><em>This email was automatically generated by your English Vocabulary Service.</em></p>
                    </div>
                </body>
                </html>
                """,
                LocalDate.now().format(DateTimeFormatter.ofPattern("EEEE, MMMM dd, yyyy")),
                content.replace("\n", "\n"));
    }
}
